services:
  - type: web
    name: cardoc-api
    env: python
    plan: free          # switch to “starter” or higher any time

    # ── Build container (read-only) ─────────────────────────
    buildCommand: pip install -r requirements.txt

    # ── Runtime container (disk is mounted) ─────────────────
    startCommand: |
      python download_models.py && \
      gunicorn app:app \
        --bind 0.0.0.0:$PORT \
        --workers 2 --threads 4 \
        --timeout 120            # gevent flag removed

    # ── Persistent disk for model weights ───────────────────
    disks:
      - name: cardoc-models
        mountPath: /var/models
        sizeGB: 1
