# ─────────────────────────────────────────────────────────────
#  render.yaml  ─ Cardoc-API deployment blueprint
# ─────────────────────────────────────────────────────────────
services:
  - type: web
    name: cardoc-api                          # the Render service name
    env: python                               # use Render’s Python image
    plan: free                                # bump to “starter” any time

    # ── Build container (read-only filesystem) ──────────────
    # Install all Python deps; models are *not* downloaded here.
    buildCommand: |
      pip install -r requirements.txt

    # ── Runtime container (disk is mounted read-write) ──────
    # 1️⃣ ensure weights exist (skip if already cached)
    # 2️⃣ start Gunicorn with sync/thread workers (no gevent)
    startCommand: |
      python download_models.py && \
      gunicorn app:app \
        --bind 0.0.0.0:$PORT \
        --workers 2 --threads 4 \
        --timeout 120

    # ── Persistent disk for model checkpoints ───────────────
    disks:
      - name: cardoc-models                 # arbitrary label
        mountPath: /var/models              # download_models.py writes here
        sizeGB: 1                           # 640 MB weights + safety margin
