# ───────── cardoc-api-2 – Render service definition ─────────
services:
  - type: web
    name: cardoc-api-2          # keep the exact name Render shows
    env: python
    plan: standard              # or starter / free — whatever you use

    # ── Build container ─────────────────────────────────────
    buildCommand: |
      pip install -r requirements.txt

    # ── Runtime container ───────────────────────────────────
    startCommand: |
      # activate Render’s virtual-env so /.venv/bin is on PATH
      . /.venv/bin/activate
      #
      # make sure the persistent disk exists & is writable
      mkdir -p /var/models && chown -R "$(id -u):$(id -g)" /var/models
      #
      # download any missing model weights (no-op if already there)
      python download_models.py
      #
      # start the API server
      gunicorn app:app \
        --bind 0.0.0.0:$PORT \
        --workers 2 --threads 4 \
        --timeout 120            # gthread workers (default)

    # ── Persistent disk for model weights ───────────────────
    disks:
      - name: cardoc-models
        mountPath: /var/models
        sizeGB: 2                # 1 GB is fine; bump if you need more
