# ───────── cardoc-api – Render service definition ─────────
services:
  - type: web
    name: cardoc-api
    env: python
    plan: free          # bump to “starter” or higher any time

    # ── Build container (read-only FS) ──────────────────────
    buildCommand: pip install -r requirements.txt

    # ── Runtime container (disk is mounted) ────────────────
    startCommand: |
      python download_models.py && \
      gunicorn app:app \
        --bind 0.0.0.0:$PORT \
        --workers 2 --threads 4 \
        --timeout 120

    # ── Persistent disk for the model weights ──────────────
    disks:
      - name: cardoc-models
        mountPath: /var/models
        sizeGB: 1
