# ─────────── render.yaml (replace the whole file with this) ───────────
services:
  - type: web
    name: cardoc-api
    env: python
    plan: free               # bump to “starter” whenever you need more RAM

    # Build container (read-only)
    buildCommand: pip install -r requirements.txt        # installs gunicorn too

    # Runtime container (persistent disk is mounted)
    startCommand: >
      python download_models.py &&
      gunicorn app:app
      --bind 0.0.0.0:$PORT
      --workers 2 --threads 4
      --timeout 120           # **no gevent flag, no back-slashes**

    # Persistent disk for the weight files
    disks:
      - name: cardoc-models
        mountPath: /var/models
        sizeGB: 1
