# ───────── cardoc-api-2 – Render service definition ─────────
services:
  - type: web
    name: cardoc-api-2          # ← must match the name Render shows
    env: python
    plan: standard              # or starter / free — whatever you use

    # ── Build container (read-only) ──────────────────────────
    buildCommand: |
      pip install -r requirements.txt

    # ── Runtime container (disk is mounted) ─────────────────
    startCommand: |
      # 1) be sure scripts + python are on PATH
      export PATH="$PATH:/opt/render/.local/bin:/usr/local/python3/bin"

      # 2) download any missing model files into the persistent disk
      python3 download_models.py

      # 3) launch the Flask API behind Gunicorn (sync gthread workers)
      gunicorn app:app \
        --bind 0.0.0.0:$PORT \
        --workers 2 --threads 4 \
        --timeout 120          # adjust if you need longer requests

    # (optional) – fetch the weights during image build instead.
    # preDeployCommand: |
    #   export PATH="$PATH:/opt/render/.local/bin:/usr/local/python3/bin"
    #   python3 download_models.py

    # ── Persistent disk for model weights ───────────────────
    disks:
      - name: cardoc-models
        mountPath: /var/models
        sizeGB: 2              # 1 GB is fine; bump if you need more
