# ── cardoc-api – Render service ─────────────────────────────
services:
  - type: web
    name: cardoc-api
    env: python          # keep whatever plan you need
    plan: free

    # Install deps in the **build** container
    buildCommand: pip install -r requirements.txt

    # Runtime container – weights disk is mounted
    startCommand: >
      export PATH=$PATH:/usr/local/python3/bin &&
      python download_models.py &&
      gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120

    disks:
      - name: cardoc-models
        mountPath: /var/models
        sizeGB: 1
