services:
  - type: web
    name: cardoc-api
    env: python
    plan: free          # ← keep whatever plan you’re on (“starter”, etc.)

    # ── Build container ───────────────────────────────────────
    buildCommand: pip install -r requirements.txt

    # ── Runtime container ─────────────────────────────────────
    startCommand: |
      python download_models.py && \
      gunicorn app:app \
        --bind 0.0.0.0:$PORT \
        --workers 2 --threads 4 \
        --timeout 120           # ← (--worker-class gevent removed)

    # ── Persistent disk for model weights ─────────────────────
    disks:
      - name: cardoc-models
        mountPath: /var/models
        sizeGB: 1
