# ───────── cardoc-api – Render service definition ─────────
services:
  - type: web
    name: cardoc-api
    env: python
    plan: free                  # change to “starter” or higher if you need more RAM

    # ── Build phase (read-only container) ──────────────────
    buildCommand: pip install -r requirements.txt

    # ── Runtime phase (disk is mounted) ───────────────────
    #   • back-slash continues the line, **no leading spaces**
    startCommand: |
      python download_models.py && \
      gunicorn app:app \
        --bind 0.0.0.0:$PORT \
        --workers 2 --threads 4 \
        --timeout 120

    # ── Persistent disk for the model weights ─────────────
    disks:
      - name: cardoc-models
        mountPath: /var/models      # download_models.py writes here
        sizeGB: 1
