# render.yaml  ── Infrastructure-as-Code for Render
services:
  - type: web
    name: cardoc-api
    env: python
    plan: starter        # keep “starter” (2 GB) or higher; “free” will OOM

    # ── Build phase ───────────────────────────────────────────
    buildCommand: >
      pip install -r requirements.txt

    # ── Runtime phase ─────────────────────────────────────────
    startCommand: |
      python download_models.py && \
      gunicorn app:app \
        --bind 0.0.0.0:$PORT \
        --workers 2 \
        --threads 4 \
        --worker-class gthread \
        --timeout 120

    # ── Persistent disk for model checkpoints ────────────────
    disks:
      - name: cardoc-models
        mountPath: /var/models
        sizeGB: 1
