services:
  - type: web
    name: cardoc-api
    env: python
    plan: free

    # ── Build container ── (read-only) ─────────────────────────
    buildCommand: pip install -r requirements.txt

    # ── Runtime container ─ (disk is mounted) ──────────────────
    startCommand: |
      python download_models.py && \
      gunicorn app:app \
        --bind 0.0.0.0:$PORT \
        --worker-class gevent \
        --timeout 120

    disks:
      - name: cardoc-models
        mountPath: /var/models     # download_models.py writes here
        sizeGB: 1
