services:
  - type: web
    name: cardoc-api
    env: python
    plan: free

    # Build container → only install deps
    buildCommand: pip install -r requirements.txt

    # Runtime container → download weights, then start Gunicorn
    startCommand: |
      python download_models.py &&
      gunicorn app:app --bind 0.0.0.0:$PORT --worker-class gevent --timeout 120

    disks:
      - name: cardoc-models
        mountPath: /var/models     # writable **only** at runtime
        sizeGB: 1
