# ───────── cardoc-api – Render service definition ─────────
services:
  - type: web
    name: cardoc-api
    env: python
    plan: starter            # free|starter|standard – pick the one you pay for

    # ── Build container (read-only file-system) ────────────
    buildCommand: pip install -r requirements.txt

    # ── Runtime container (persistent disk is mounted) ─────
    startCommand: |
      python download_models.py && \
      gunicorn app:app \
        --bind 0.0.0.0:$PORT \
        --workers 2 \
        --threads 4 \
        --timeout 120         # **NO gevent flag**

    # ── Persistent disk for model weights ───────────────────
    disks:
      - name: cardoc-models
        mountPath: /var/models
        sizeGB: 1
