# ───────── cardoc-api-2 – Render service definition ─────────
services:
  - type: web
    name: cardoc-api-2
    env: python
    plan: starter             # or standard / free

    buildCommand: |
      pip install --upgrade pip            # keeps pip warning away
      pip install -r requirements.txt

    startCommand: |
      export PATH="$PATH:/opt/render/.local/bin" && \
      python download_models.py && \
      gunicorn app:app \
        --bind 0.0.0.0:$PORT \
        --workers 2 --threads 4 \
        --timeout 120

    disks:
      - name: cardoc-models
        mountPath: /var/models
        sizeGB: 2
