# ───────── cardoc-api  (Render service definition) ─────────
services:
  - type: web
    name: cardoc-api
    env: python
    plan: starter        # <-- change back to “free” if you really need to

    # build container (read-only FS)
    buildCommand: |
      pip install --upgrade pip      #  ⇦ not required, but avoids the PEP 668 noise
      pip install -r requirements.txt

    # runtime container (persistent disk is mounted)
    startCommand: |
      python download_models.py && \
      python -m gunicorn app:app \
        --bind 0.0.0.0:$PORT \
        --workers 2 \
        --threads 4 \
        --timeout 120

    # 1 GB persistent disk for the *.pth weights
    disks:
      - name: cardoc-models
        mountPath: /var/models
        sizeGB: 1
