services:
  - type: web
    name: cardoc-api-2        # EXACT service name in Render
    env: python
    plan: standard            # or starter/free – keep yours

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    preDeployCommand: |
      python download_models.py          # puts weights into /var/models/weights

    startCommand: |
      # ── activate Render’s v-env so /.venv/bin is on $PATH
      . /.venv/bin/activate
      #
      # start the API
      gunicorn app:app \
        --bind 0.0.0.0:$PORT \
        --workers 2 --threads 4 \
        --timeout 120

    disks:
      - name: cardoc-models
        mountPath: /var/models
        sizeGB: 2
