# ───────── cardoc-api-2 – Render service definition ─────────
services:
  - type: web
    name: cardoc-api-2          # must match the service’s UI name
    env: python
    plan: standard              # or starter / free

    # ---------- Build step (read-only FS) ----------
    buildCommand: |
      pip install -r requirements.txt

    # ---------- Runtime (persistent disk is mounted) ----------
    startCommand: |
      # 1) download weights to /var/models/weights   (no-op if cached)
      python3 download_models.py

      # 2) launch the Flask API behind Gunicorn (sync/gthread workers)
      gunicorn app:app \
        --bind 0.0.0.0:$PORT \
        --workers 2 --threads 4 \
        --timeout 120

    # ---------- Persistent disk for model weights ----------
    disks:
      - name: cardoc-models
        mountPath: /var/models
        sizeGB: 2   # adjust if you need more
