services:
  - type: web
    name: cardoc-api-2
    env: python
    plan: standard

    buildCommand: |
      pip install -r requirements.txt
      # optional but faster: download weights during build
      python3 download_models.py

    startCommand: |
      python3 download_models.py \
      && gunicorn app:app \
           --bind 0.0.0.0:$PORT \
           --workers 2 --threads 4 \
           --timeout 120

    healthCheckPath: /predict  # ← this fixes the 502 without editing app.py

    disks:
      - name: cardoc-models
        mountPath: /var/models
        sizeGB: 2
